FROM rockylinux:9
RUN yum install curl
RUN yum install -y curl
RUN yum -y install curl
RUN yum --assumeyes install curl
RUN yum update curl
RUN echo yum install curl
RUN cd /tmp && yum install make
RUN yum --installroot /mnt install tar
RUN yum --setopt tsflags=nodocs install -y gzip
RUN yum --config install update curl
