FROM alpine:3.20
LABEL org.opencontainers.image.title="rudolint"
LABEL org.opencontainers.image.source="https://github.com/kubeply/rudolint"
LABEL com.example.extra="extra"
LABEL org.opencontainers.image.title="rudolint" com.example.another="extra"
