[package]
name = "rudolint-bench"
version.workspace = true
edition.workspace = true
description = "Benchmark harness support for rudolint"
license.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]
criterion = { version = "4.6.0", package = "codspeed-criterion-compat" }
rudolint-config = { path = "../rudolint-config" }
rudolint-dockerfile = { path = "../rudolint-dockerfile" }
rudolint-output = { path = "../rudolint-output" }
rudolint-rules = { path = "../rudolint-rules" }

[[bench]]
name = "rudolint_benchmarks"
harness = false
