[package]
name = "rudolint-dockerfile"
version.workspace = true
edition.workspace = true
description = "Dockerfile parsing for rudolint"
license.workspace = true
repository.workspace = true

[dependencies]
regex.workspace = true
rudolint-source = { path = "../rudolint-source" }

[dev-dependencies]
insta.workspace = true
rudolint-test.workspace = true
serde_json.workspace = true
