[package]
name = "rudolint"
version.workspace = true
edition.workspace = true
description = "BuildKit-native Dockerfile linter"
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ignore.workspace = true
rudolint-config.workspace = true
rudolint-diagnostics.workspace = true
rudolint-dockerfile.workspace = true
rudolint-fix.workspace = true
rudolint-output.workspace = true
rudolint-rules.workspace = true
rudolint-settings.workspace = true
rudolint-source.workspace = true
semver.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
insta.workspace = true
jsonschema.workspace = true
predicates.workspace = true
rudolint-test.workspace = true
tempfile.workspace = true
