FROM ubuntu:24.04
RUN apt-get update
RUN apt-get install curl=8.5.0-2ubuntu10.6
RUN apt-get -y install curl=8.5.0-2ubuntu10.6
RUN apt-get install -y curl=8.5.0-2ubuntu10.6
RUN apt-get install -yq curl=8.5.0-2ubuntu10.6
RUN apt-get install -qy curl=8.5.0-2ubuntu10.6
RUN apt-get -yq install curl=8.5.0-2ubuntu10.6
RUN apt-get install --yes curl=8.5.0-2ubuntu10.6
RUN apt-get install --assume-yes curl=8.5.0-2ubuntu10.6
RUN apt-get install -oAcquire::Retries=3 curl=8.5.0-2ubuntu10.6
RUN echo apt-get install curl
RUN cd /tmp && apt-get install make=4.3-4.1build2
