FROM alpine:3.20
LABEL org.opencontainers.image.revision="abc1234"
LABEL org.opencontainers.image.revision="0123456789abcdef0123456789abcdef01234567"
LABEL org.opencontainers.image.revision="ABC1234"
LABEL org.opencontainers.image.revision="abc123"
LABEL org.opencontainers.image.revision="abc123g"
LABEL org.opencontainers.image.revision=""
LABEL org.opencontainers.image.title="ABC1234"
