FROM alpine:3.20
LABEL org.opencontainers.image.licenses="Apache 2"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.licenses="LicenseRef-Proprietary"
LABEL org.opencontainers.image.licenses=""
LABEL org.opencontainers.image.title="Apache 2"
