[package]
name = "rudolint-settings"
version.workspace = true
edition.workspace = true
description = "Resolved settings for rudolint"
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
rudolint-config.workspace = true

[dev-dependencies]
tempfile.workspace = true
