FROM alpine:latest

FROM docker.io/library/alpine:latest

FROM localhost:5000/alpine:latest

FROM alpine:3.20

FROM alpine

FROM alpine:latest@sha256:2c047404e52a3cfceb09e5c46f73076d8a3cf9931d9b145438cdd093b87aa970

FROM scratch

FROM alpine:3.20 AS latest

FROM latest AS copied_from_stage
