[package]
name = "rudolint-lsp"
version.workspace = true
edition.workspace = true
description = "Language server support for rudolint"
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
lsp-types.workspace = true
rudolint-config.workspace = true
rudolint-diagnostics.workspace = true
rudolint-dockerfile.workspace = true
rudolint-fix.workspace = true
rudolint-rules.workspace = true
rudolint-settings.workspace = true
rudolint-source.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
