[package]
name = "rudolint-lsp"
version.workspace = true
edition.workspace = true
description = "Language server support for rudolint"
license.workspace = true
repository.workspace = true

[dependencies]
lsp-types.workspace = true
rudolint-diagnostics.workspace = true
rudolint-source.workspace = true
