FROM alpine:3.20
LABEL org.opencontainers.image.version="1.2.3"
LABEL org.opencontainers.image.version="1.2.3-alpha.1+build.5"
LABEL org.opencontainers.image.version="v1.2.3"
LABEL org.opencontainers.image.version="1.2"
LABEL org.opencontainers.image.version="1.2.3.4"
LABEL org.opencontainers.image.version=""
LABEL org.opencontainers.image.title="v1.2.3"
