[package]
name = "rudolint-diagnostics"
version.workspace = true
edition.workspace = true
description = "Diagnostic types for rudolint"
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
rudolint-source = { path = "../rudolint-source" }
serde.workspace = true
