FROM opensuse/leap:15.6
RUN zypper install curl
RUN zypper install -y curl
RUN zypper -n install curl
RUN zypper --non-interactive install curl
RUN zypper update curl
RUN echo zypper install curl
RUN cd /tmp && zypper install make
