FROM ubuntu:24.04
RUN apt-get update
RUN apt-get update && apt-get install -y curl=8.5.0-2ubuntu10.6
RUN apt-get update && apt-get install -y curl=8.5.0-2ubuntu10.6 && rm -rf /var/lib/apt/lists/*
RUN echo apt-get update
RUN apt-get download update
RUN apt-get update && rm -rf /tmp/var/lib/apt/lists-backup
RUN rm -rf /var/lib/apt/lists/*
